packages:
  core: !include panel.yaml

esphome:
  project:
    name: dflourusso.ha-touch-panel
    version: "1.0.0"

http_request:

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: Firmware
    device_class: firmware
    source: https://dflourusso.github.io/ha-touch-panel/firmware/home-suite.manifest.json
